### ISSUE TITLE
Show list of all_followers? recursively in list?

### ISSUE THREAD

**Issue by ghost** [lastomato/mongoid_followable#1]
Is there a way to add all_followers to a list where each member of the array is displayed separately in each <li></li> tag?

**Comment by lastomato** [comment]
As the all_followers method return an array, consequently you are able to do this in your view (for example in show.html.erb):

<%= @someuser.all_followers.each do |follower| %>
  < li ><%= follower.name %>< /li > #do something here
<%= end %>

In this way, all_followers are displayed inside separate list tag (< li >< /li >)

PS: < li > seems to be transferred automatically here.

**Comment by ghost** [comment]
aha that's what i was missing! i was writing it as <%= @someuser.all_followers.each do |someuser| %> and it was pulling the entire array. that proved to be quite interesting to say the least. i managed to get each item listed, but only after converting to xml...knew there had to be a simpler way! thanks. great job btw.
