### ISSUE TITLE
Pointing to follow method within link_to or button_to?

### ISSUE THREAD

**Issue by ghost** [lastomato/mongoid_followable#2]
How would you use @someuser.follow(@anotheruser) within a link_to or button_to tag? I've tried several different methods and am currently just calling it from within link_to as <%= link_to "Follow", someuser.follow(anotheruser) %> but of course, the function is called whenever the page is loaded AND when the link is clicked. This is fine on pages only calling the function once, but in others (say a user directory), it just reverses the follow/unfollow whenever the page is load.

Ideas?

**Comment by lastomato** [comment]
I guess that you want to make it an ajax request. Generally, you can write a method for this in your controller, and make it respond to ajax request. Meanwhile, add a 'remote => true' attribute to wherever you put your "Follow" button. Actually, it's quite a long story and impossible for me to give all the details here. So, I recommend you to check some rails books like ruby tutorials http://ruby.railstutorial.org/ and rails guides http://guides.rubyonrails.org.

Good luck!
