### ISSUE TITLE
Too complex!

### ISSUE THREAD

**Issue by huacnlee** [lastomato/mongoid_followable#4]

**Comment by lastomato** [comment]
How come? Any suggestions?

**Comment by huacnlee** [comment]
Why should need `cannot_follow,set_authorization,unset_authorization, follow_history`, that looks like spacial, don't useful for every project.

**Comment by lastomato** [comment]
It may be useful in some scenarios like authorization controlling, data mining/recommendation. Anyway, I think it would be better to give users the ability to do sth. and leave them to decide whether to use it.

**Comment by huacnlee** [comment]
@lastomato But when I don't need them, would this do not store in MongoDB as a empty Array field.

**Comment by lastomato** [comment]
Right, really a waste if not needed. Gonna do some optimization this weekend. Thanks!

**Comment by lastomato** [comment]
See [mongo_followable](https://github.com/lastomato/mongo_followable) for reference.
